### ISSUE TITLE
preprocess data bug

### ISSUE THREAD

**Issue by llllly26** [CarbonMatrixLab/AbX#1]
Congratulations on your great work! 
I met some bugs when processing the dataset.
To preprocess the structure data into `.npz` format, use the` preprocess_data.py` script following your released:
`python preprocess_data.py --cpu 100 --summary_file ./data/sabdab_summary_all.tsv --data_dir ./data/mmcif --output_dir ./data/npz --data_mode mmcif`
unfortunately, there is nothing returned, as illustrated below.
![image](https://github.com/user-attachments/assets/e2b9b03d-22b0-4769-9bf7-37a8f76d3cee)
I debug the code about  `preprocess_data.py` ,the code that `from abx.preprocess.make_ab_data_from_mmcif import main` import a `main` function, but `main` function using `process` function to deal with `parse_list`, but I can not run into `process` function and when I finished `parse_list`, the procedure stop and return nothing. 
![image](https://github.com/user-attachments/assets/cc473446-5e52-4300-b2f7-7be1e03a60ea)

could you give some solution? thanks!

You recommend using the mmCIF format for PDB structures, as it provides comprehensive information. By the way,  the dataset released only have PDB format, to use mmCIF, if there is any Post-processing or processed data? thanks!

**Comment by CarbonMatrixLab** [comment]
We have fix the problem, you can check these codes now

**Comment by RyanYip-Kat** [comment]
> Owner
No.It still has the same issue.this program can not handle pdb files.
